ALTER TABLE tasks ADD COLUMN block_priority INTEGER DEFAULT 50;
ALTER TABLE tasks ADD COLUMN subblock_priority INTEGER DEFAULT 50;
ALTER TABLE tasks ADD COLUMN agent_minutes INTEGER DEFAULT 15;
ALTER TABLE tasks ADD COLUMN tenant_id TEXT DEFAULT 'core';
ALTER TABLE tasks ADD COLUMN created_at TEXT;
ALTER TABLE tasks ADD COLUMN updated_at TEXT;
